### ISSUE TITLE
Erro do tom cat

### ISSUE THREAD

**Issue by Danielgol** [ifpe-cti/atomoids#5]
@fabriciofx este foi o erro que deu no tom cat

GRAVE: Error configuring application listener of class org.jboss.weld.environment.servlet.Listener
java.lang.ClassNotFoundException: org.jboss.weld.environment.servlet.Listener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4660)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by fabriciofx** [comment]
@Danielgol 

Foi adicionado um plugin do maven que permite executar o tomcat de forma embedded. Assim, atualize o seu código (git pull) e no terminal, execute: mvn clean package. Depois para executar o tomcat, execute: mvn tomcat7:run

Abra então um browser e abra a página: http://localhost:8080/atomoids

Se esta solução resolver o problema, confirme que resolveu e feche a issue. Caso contrário, escreva aqui por que esta solução não é adequada para o problema.

**Comment by Danielgol** [comment]
O Problema foi resolvido!!!
